name: CI

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        rust: ["stable", "beta", "nightly"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build
      run: cargo build
